### ISSUE TITLE
Feature request: First results should cover the whole table view without "loading..."

### ISSUE THREAD

**Issue by gerchicov-bp** [AfrozZaheer/AZTableView#1]
Run an example on iphone 5s simulator and do nothing more. You see the following stages:
1)"Loading..."
2)some values and "Loading..."
3)more values without "Loading...".
What about to replace 2 with 1? I mean showing single "Loading..." label until you get a data that can fulfill at least the whole table height

**Comment by AfrozZaheer** [comment]
Hi Gerchicov-bp, 
What I assumed you want to show data more than tableview height. Well, it depend upon your service request. In actual service probably you send parameters, page size, pageNumber etc page size determine number of items fetched in one service call. You can do that simply by increasing pagesize in FakeService.swift. Right now pagesize is 10 so service is fetching data 10 by 10 in each call.
Hope this will clear you understanding.

**Comment by gerchicov-bp** [comment]
@AfrozZaheer hello but it won't solve the problem:
- different devices have different table height. The same page size for ipad pro and iphone 5?
- on app launch the control is empty and first data batch is needed to fulfill the control with any data
You can also check app store with tables of dynamic size - they don't have items and "Loading" simultaneously until you scroll them. And it seems their pages are all of different size - not only the first one

**Comment by fahidattique55** [comment]
Hi gerchicov-bp,

There are two ways to do that,

1. You know the cell height and table view's frame height so you can calculate the number of rows and set it as pageSize, so that user won't see the 'loading' view.

2. increase the page size to a large value like 20 or 25 so that 'loading' view will not be shown to user

I will recommend simply make page size a large number as discussed above in point#2, which is much easy way to achieve what you want.

Thanks & Regards
